export const positions = [
  { name: 'OA', value: 'OA', image: '/assets/images/positions/OA.png' },
  { name: 'OP', value: 'OP', image: '/assets/images/positions/OP.png' },
  { name: 'ROT', value: 'ROT', image: '/assets/images/positions/ROT.png' },
  { name: 'LOT', value: 'LOT', image: '/assets/images/positions/LOT.png' },
  { name: 'ROA', value: 'ROA', image: '/assets/images/positions/ROA.png' },
  { name: 'ROP', value: 'ROP', image: '/assets/images/positions/ROP.png' },
  { name: 'LOA', value: 'LOA', image: '/assets/images/positions/LOA.png' },
  { name: 'LOP', value: 'LOP', image: '/assets/images/positions/LOP.png' },
  { name: 'LP', value: 'LP', image: '/assets/images/positions/dryclean.png' },
];

export const ociputData = [
  { name: 'Occiput', value: 'Occiput' },
  { name: 'Brow', value: 'Brow' },
  { name: 'Face', value: 'Face' },
  { name: 'Arm', value: 'Arm' },
  { name: 'Breech', value: 'Breech' },
];

export const cDilationData = [
  { number: 1 },
  { number: 2 },
  { number: 3 },
  { number: 4 },
  { number: 5 },
  { number: 6 },
  { number: 7 },
  { number: 8 },
  { number: 9 },
  { number: 10 },
];

export const cLength = [{ number: 1 }, { number: 2 }, { number: 3 }];

export const aboveBrimsData = [{ number: 1 }, { number: 2 }, { number: 3 }, { number: 4 }, { number: 5 }];

export const Pcfrequency = [{ number: 1 }, { number: 2 }, { number: 3 }, { number: 4 }, { number: 5 }];

export const Pcduration = [
  { number: 1 },
  { number: 2 },
  { number: 3 },
  { number: 4 },
  { number: 5 },
  { number: 6 },
  { number: 7 },
  { number: 8 },
  { number: 9 },
  { number: 10 },
  { number: 11 },
  { number: 12 },
  { number: 13 },
  { number: 14 },
  { number: 15 },
  { number: 16 },
  { number: 17 },
  { number: 18 },
  { number: 19 },
  { number: 20 },
  { number: 21 },
  { number: 22 },
  { number: 23 },
  { number: 24 },
  { number: 25 },
  { number: 26 },
  { number: 27 },
  { number: 28 },
  { number: 29 },
  { number: 30 },
  { number: 31 },
  { number: 32 },
  { number: 33 },
  { number: 34 },
  { number: 35 },
  { number: 36 },
  { number: 37 },
  { number: 38 },
  { number: 39 },
  { number: 41 },
  { number: 42 },
  { number: 43 },
  { number: 44 },
  { number: 45 },
  { number: 46 },
  { number: 47 },
  { number: 48 },
  { number: 49 },
  { number: 50 },
  { number: 51 },
  { number: 52 },
  { number: 53 },
  { number: 54 },
  { number: 55 },
  { number: 56 },
  { number: 57 },
  { number: 58 },
  { number: 59 },
  { number: 60 },
];

export const initialNullArray = [
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
];
export const xAxisLabels = [
  '00:00',
  '00:30',
  '01:00',
  '01:30',
  '02:00',
  '02:30',
  '03:00',
  '03:30',
  '04:00',
  '04:30',
  '05:00',
  '05:30',
  '06:00',
  '06:30',
  '07:00',
  '07:30',
  '08:00',
  '08:30',
  '09:00',
  '09:30',
  '10:00',
  '10:30',
  '11:00',
  '11:30',
  '12:00',
  '12:30',
  '13:00',
  '13:30',
  '14:00',
  '14:30',
  '15:00',
  '15:30',
  '16:00',
  '16:30',
  '17:00',
  '17:30',
  '18:00',
  '18:30',
  '19:00',
  '19:30',
  '20:00',
  '20:30',
  '21:00',
  '21:30',
  '22:00',
  '22:30',
  '23:00',
  '23:30',
  '24:00',
];
